version: "3.9"
services:
  app:
    build: .
    volumes:
      - ./:/code/
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ".env.docker"
    restart: "always"

  db:
    image: mongo
    volumes:
      - "mongodb_data:/data/db"
    ports:
      - "27018:27017"
    restart: "always"

volumes:
  mongodb_data:
